export const SET_LOCATION = "SET_LOCATION";
export const TRY_AUTH = 'TRY_AUTH';

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN"; 

export const SET_DEVICES = "SET_DEVICES"; 
export const INIT_DEVICES_ASYNC = "INIT_DEVICES_ASYNC";
export const BLOCK_DEVICE = "BLOCK_DEVICE";